spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  kafka:
    listener:
      idle-event-interval:
      idle-partition-event-interval:


logging:
  level:
    com.example: debug
  pattern:
    dateformat: HH:mm:ss

bigevent:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: burtry-bigevent