spring:
  datasource:
    driver-class-name: ${bigevent.datasource.driver-class-name}
    url: ${bigevent.datasource.url}
    username: ${bigevent.datasource.username}
    password: ${bigevent.datasource.password}
  kafka:
    listener:
      idle-event-interval:
      idle-partition-event-interval:
  profiles:
    active: dev

logging:
  level:
    com.example: debug
  pattern:
    dateformat: HH:mm:ss

bigevent:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: burtry-bigevent
server:
  port: ${bigevent.server.port}

