spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: com.itheima.mp.domain.po
  global-config:
    db-config:
      id-type: auto

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 后端管理接口
      packages-to-scan: com.itheima.mp.controller.admin
    - group: 前端API接口
      packages-to-scan: com.itheima.mp.controller.user

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN
